# -*- coding: utf-8 -*-
"""ExerciciosFor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bNId86hWCqg8DSX8enZ6mzmsUAcI_NuI

Faça um programa que leia 5 números e informe o maior número.
"""

maior_numero = float('-inf')

for i in range(5):
  numero = float(input(f"digite o {i+1}º numero: "))
  if numero > maior_numero:
    maior_numero = numero

  print(f"O maior numero digitado é: {maior_numero}")

"""Faça um programa que verifique e mostre os números entre 1.000 e 2.000
(inclusive) que, quando divididos por 11 produzam resto igual a 2.
"""

for numero in range(1000,2001):
  if numero % 11 == 2:
    print(numero)

"""Faça um programa que leia 5 números e informe a soma e a média dos
números.
"""

soma = 0

for i in range(5):
 numero = float(input(f"digite o {i+1}º numero: "))
 soma += numero
 media = soma/5

print(f'a soma é {soma} e a media é {media}')

"""Faça um programa que receba um número e usando laços de repetição
calcule e mostre a tabuada desse número.
"""

numero = int(input('Digite um numero que vc nao sabe a tabuada: '))

print(f'tabuada de {numero}')
for contador in range(1,11):
  resultado = numero * contador
  print(f'{numero} x {contador} = {resultado}')

"""Faça um programa que mostre as tabuadas dos números de 1 a 10 usando
laços de repetição.
"""

for i in range(1,11):
  print(f"Tabuada do {i}:")
  for j in range(1,11):
    resultado = i * j
    print(f'{i} x {j} = {resultado}')

"""Faça um programa que imprima na tela os números de 1 a 20, um abaixo
do outro. Depois modifique o programa para que ele mostre os números
um ao lado do outro.

"""

for i in range(1,21):
  print(i)

print(list(range(1,21)))

""" Faça um programa que imprima na tela apenas os números ímpares entre
1 e 50.
"""

for i in range(1,51):
  if i % 2 == 1:
   print(i)

"""Faça um programa que receba dois números inteiros e gere os números
inteiros que estão no intervalo compreendido por eles.
"""

num1 = int(input('escolha um numero menor que o segundo que você colocar: '))
num2 = int(input('escolha outro numero: '))

for contagem in range(num1+1,num2):
  print(contagem)

""" Uma loja deseja cadastrar 5 clientes e verificar se o faturamento da loja foi
superior a loja B (faturamento = 54000). Se o faturamento atingir esse valor
mostre na tela uma mensagem contendo em quanto foi superado o
faturamento.
"""

loja2 = 54000
soma = 0
for i in range(5):
  loja1 = float(input(f'informe o faturamento do {i+1}* cliente: '))
  soma += loja1
if soma > loja2:
    print(f'vocês faturaram! O faturamento da loja A em realação da B foi de {soma - loja2}')
else:
  print('vcs nao faturaram')

"""Faça um programa que peça 10 números inteiros, calcule e mostre a
quantidade de números pares e a quantidade de números impares
"""

par = 0
impar = 0

for i in range(10):
  numero = int(input(f'informe o {i + 1}* valor: '))
  if numero % 2 == 0:
    par+= 1
  elif numero % 2 == 1:
    impar+=1

print(f'quantidade de pares: {par}')
print(f'quantidade de impares: {impar}')

nota = int(input("Digite uma nota entre zero e dez: "))

for i in range(9999999999999):
  if nota <0 or nota > 10:
    print('Nota invalida')
    nota = int(input("Digite uma nota entre zero e dez: "))
  else:
    print('nota valida')
    break

"""Um funcionário de uma empresa recebe aumento salarial anualmente:
Sabe-se que:
Esse funcionário foi contratado em 1995, com salário inicial de R$ 1.000,00;
Em 1996 recebeu aumento de 1,5% sobre seu salário inicial;
A partir de 1997 (inclusive), os aumentos salariais sempre correspondem ao
dobro do percentual do ano anterior. Faça um programa que determine o
salário atual desse funcionário. Após concluir isto, altere o programa
permitindo que o usuário digite o salário inicial do funcionário.
"""

#recebe aumento anualmente
#foi contratado em 1995
#salario inicial de 1000
#em 1996 recebeu 1,5% a mais que o salario
#97 inclusive dobro do ano anterior %

salario = float(input('Digite o salario inicial do funcionário: '))
percentual = 0.015

for i in range(1996,2025):
  aumento = salario * percentual
  aumento += aumento
  percentual *= 2
  print(f'salario em {i} = {aumento: .2f}')

"""Uma loja tem tem uma política de descontos de acordo com o valor da
compra do cliente. Os descontos começam acima dos R$500. A cada 100
reais acima dos R$500,00 o cliente ganha 1% de desconto cumulativo até
25%.
Por exemplo: R$500 = 1% || R$600,00 = 2% … etc…
Faça um programa que exiba essa tabela de descontos no seguinte formato:
Valordacompra – porcentagem de desconto – valor final
"""

valor = float(input('Informe o valor do produto: R$ '))
contador = 2

if valor >=600:
  reduzido = valor - 500
  if reduzido >= 100 or contador <=24:
    for i in range(999):
      contador += 1
      reduzido -= 100
      if reduzido < 100 or contador == 24:
        break

  porcentagem = contador / 100
  desconto = valor * porcentagem
  final = valor - desconto
  print(f'o produto de R${valor: .2f} ficara a partir de R${final: .2f} com um desconto de {desconto: .2f}%')

ate15= 0
de16a30 = 0
de31a45 = 0
de46a60 = 0
mais61 =  0
for i in range(15):
  idade = int(input(f'Digite a idade da {i+1}* pessoa'))
  if idade <=15
    ate15 +=1
  elif idade >=16 and idade <=30:
    de16a30+=1
  elif idade >=31 and idade <=45:
    de31a45+=1
  elif idade >=46 and idade <=60:
    de46a60+=1
  elif idade >60:
    mais61+=1

print(f'a quantidade de pessoas por faixa etaria de ')



